### ISSUE TITLE
Images to left or right of text are not consistently working correctly

### ISSUE THREAD

**Issue by catlook** [rackerlabs/technical-blog#150]
See this post: https://docs.rackspace.com/blog/crashing-through-silos-with-the-rackspace-process-engineering-group/.

The first image (to the right of text) and appearing above the  line) works great.  Text flows appropriately and font is sized correctly.  

The second image is supposed to be to the left of text and is wrong.  Only one line of text is beside the image, instead of the whole paragraph, and the font is smaller than the rest of the post.  This happens whether the image is to the left or the right.

**Comment by robb-romans** [comment]
@catlook thanks. Would you please provide two more blogs that show this issue? Screenshots helpful.

**Comment by catlook** [comment]
Another example of a bad post: https://deploy-preview-149--docs-technical-blog.netlify.app/blog/aws-outposts-a-hybrid-approach-to-designing-hybrid-environments-part-two/

**Comment by catlook** [comment]
![image](https://user-images.githubusercontent.com/5709104/88848680-707d5c80-d1ae-11ea-8bfe-4cf55d442875.png)

**Comment by catlook** [comment]
![image](https://user-images.githubusercontent.com/5709104/88848780-8db22b00-d1ae-11ea-9b9c-b991bdeb3f63.png)

**Comment by catlook** [comment]
that last one shows text flow and font-size issue.

**Comment by catlook** [comment]
This is another successful above the line example: 
![image](https://user-images.githubusercontent.com/5709104/88849342-5abc6700-d1af-11ea-93ad-a8036fe6724f.png)

**Comment by catlook** [comment]
This is fixed.  Ravi changed the short code for image to img
