### ISSUE TITLE
Schedule future publish

### ISSUE THREAD

**Issue by catlook** [rackerlabs/technical-blog#159]
Problem a: If I merge a future-dated PR, the post will not actually publish until the first netlify build on the publish date.  

Problem b: Sometimes, an author wants a blog post to publish at a specific time to coincide with a planned publicity release.

Request: How can I schedule a job to automatically kick off a netlify build on a specific date at a specific time?

**Comment by catlook** [comment]
Is this an answer?  Can anyone help me set it up and test it?  And make sure I understand how to do it in the future and have appropriate access and permission?

https://ericjinks.com/blog/2019/netlify-scheduled-build/

**Comment by robb-romans** [comment]
Here is an additional article: https://ddbeck.com/scheduling-static-sites/

**Comment by robb-romans** [comment]
Can do this today by setting the post date to a future date. It will build and show in the PR preview, but not show in production until after the date set. It will be published in the next production build on or after that date.

**Comment by catlook** [comment]
WIll it publish if no other blog publishes that day?

**Comment by robb-romans** [comment]
No. It will publish on the next production build, whenever that is.
