### ISSUE TITLE
Need block quote functionality

### ISSUE THREAD

**Issue by catlook** [rackerlabs/technical-blog#169]
Markdown has a way to indicate a block quote, but deconst doesn't render it. Can Hugo/Netlify be configured to publish indented block quotes?  A candidate post: https://docs.rackspace.com/blog/integrate-oracle-adf-with-e-business-suite/

**Comment by robb-romans** [comment]
Cat, we are currently using Blackfriday Markdown syntax: https://github.com/rackerlabs/technical-blog/blob/master/config.toml#L18

Does it support this?

**Comment by catlook** [comment]
I'll test!!

**Comment by catlook** [comment]
I used the markdown block quote syntax (putting > infront of every line of the two paragraph quote), and the resulting format changed nothing.  There is no indication of a block quote:  
![image](https://user-images.githubusercontent.com/5709104/89545652-3ffa7b80-d7c9-11ea-80a5-1a1d6246db9d.png)

**Comment by catlook** [comment]
The second two paragraphs should at least have been block-indented to indicate a block quote.

**Comment by catlook** [comment]
It looks like we need to do additional work on our end to render the block quotes appropriately.
