### ISSUE TITLE
These blogs are not displaying properly- md formatting might be broken 

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/technical-blog#172]
https://docs.rackspace.com/blog/scaling-horizontally-handling-sessions-on-the-open-cloud/
 
https://docs.rackspace.com/blog/displaying-prepared-code-with-syntax-highlighting-on-android/
 
https://docs.rackspace.com/blog/speed-up-with-redis/
 
https://docs.rackspace.com/blog/powerclient-rackspace-cloud-api-powershell-client/

**Comment by codebyravi** [comment]
Fixed.
