### ISSUE TITLE
Handles poorly formated dates wrong

### ISSUE THREAD

**Issue by catlook** [rackerlabs/technical-blog#56]
This might not be something we need to fix.  However, the metadata date for https://docs-rackspace-com.netlify.app/blog/2019-12-02-nervous-about-converting-from-classic-to-lightning-learn-from-this-companys-success/ is 2019-12-2 instead of 2019-12-02.  Old system handled that gracefully and displayed it in true date sequence.  The new system posted it at the end with a date of January 1, 0001.

**Comment by codebyravi** [comment]
I fixed the date.

**Comment by catlook** [comment]
Well, this was true of several posts.  The one I provided was just an example.  I fixed all of them in the production repo, so when Robb syncs up, the problem won't exist.  But what if I accidentally enter a date like that next month?  Will Hugo handle it with grace, reject it right away, and make me fix it, or publish it but move it to the end of the list with a bad date?
