### ISSUE TITLE
Category display

### ISSUE THREAD

**Issue by catlook** [rackerlabs/technical-blog#57]
The category "SDK" is showing oddly spaced out at the top of the post.  Compare https://docs-rackspace-com.netlify.app/blog/2013-03-04-how-i-learned-ruby-on-rails/ to https://developer.rackspace.com/blog/how-i-learned-ruby-on-rails/

**Comment by catlook** [comment]
checked and the issue is still an issue.

**Comment by robb-romans** [comment]
Confirmed fixed https://docs-technical-blog.netlify.app/blog/how-i-learned-ruby-on-rails/
