### ISSUE TITLE
Link references

### ISSUE THREAD

**Issue by catlook** [rackerlabs/technical-blog#59]
Usually URL links are in line, but some older posts use a reference syntax with all links listed at the bottom of the post and referenced in text by [#].  When published, the link operates normally.  In the new system, this doesn't work.  Compare https://docs-rackspace-com.netlify.app/blog/2013-09-11-11-things/ to https://developer.rackspace.com/blog/11-things/

**Comment by codebyravi** [comment]
Fixed it
