### ISSUE TITLE
Notes and warnings

### ISSUE THREAD

**Issue by catlook** [rackerlabs/technical-blog#61]
This is not a discrepancy, but a request.  To mark a note or warning, we just bold the label.  For example, **Note**:  Pay attention to this.  Both old and new systems simply bold the label and do no other formating. I'd like the callouts to be indented or boxed or treated differently from regular text (as the How-To does).

**Comment by robb-romans** [comment]
After release

**Comment by catlook** [comment]
think this is fixed

**Comment by catlook** [comment]
closed it accidentally
