### ISSUE TITLE
Snippet pictures having problems

### ISSUE THREAD

**Issue by catlook** [rackerlabs/technical-blog#62]
In the Content/blog folder, there is a Picture1.png file in addition to all the post directories.  This picture is a duplicate of Picture1.png in **2020-06-05-crashing-through-the-silos-with-the-rackspace-process-engineering-group.** The orphan file can probably be deleted.

**Comment by codebyravi** [comment]
I placed the image inside 'static/img/2020-06-05-crashing-through-silos-with-the-rackspace-process-engineering-group/' path which makes the MD easier to find it in the list and blog as '/img/2020-06-05-crashing-through-silos-with-the-rackspace-process-engineering-group/Picture1.png' from the markdown file.

**Comment by catlook** [comment]
Great!  Since we know there are other posts that might be in the same boat, do you want to go ahead and give it a unique name?  Like PEG-logo.png   and update the file in the post itself and the reference in the post?

**Comment by catlook** [comment]
I see if I can find all the posts that have pics in the preview so we can update them.

**Comment by robb-romans** [comment]
Confirmed fixed.
