### ISSUE TITLE
Author image and bio change

### ISSUE THREAD

**Issue by catlook** [rackerlabs/technical-blog#68]
If there is no bio or image, display the name and gray silhouette image at top and nothing at the bottom. The top part works fine, but they also show at the bottom, which we don't want.

Compare: https://docs-technical-blog.netlify.app/blog/using-a-custom-kernel-with-the-ubuntu-installer/ vs. https://docs-technical-blog.netlify.app/blog/using-a-custom-kernel-with-the-ubuntu-installer/

The following variations work on the new site: 

- if there is no image, use a gray silhouette image.
- If there is an author bio and image, display name and image at the top and name, image, and bio at the bottom. 
- If there is only a bio, display name and a gray silhouette image at the top and name, bio, and a gray silhouette image at the bottom.

**Comment by robb-romans** [comment]
@catlook should be done. Please test.

**Comment by catlook** [comment]
bio without image works: https://docs-technical-blog.netlify.app/blog/use-the-sap-hybris-cache-to-improve-application-performance/
no bio and no image still show name and silhouette at the bottom: https://docs-technical-blog.netlify.app/blog/get-high-throughput-and-low-latency-with-your-nvme-enabled-dual-socket-servers/

I'd prefer no bio and no pic to show nothing, but I can live with this.
