### ISSUE TITLE
Bug: code block displays an emoji

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/technical-blog#79]
For blog post: https://docs-technical-blog.netlify.app/blog/neutron-networking-l3-agent/

There's a code block where the code sequence `:de:` gets displayed as a German flag emoji

Old version:
![Screen Shot 2020-07-22 at 10 12 41 AM](https://user-images.githubusercontent.com/12717324/88194142-1572c500-cc04-11ea-805a-4893ac0411e8.png)

Beta version:
<img width="1016" alt="Screen Shot 2020-07-22 at 10 12 34 AM" src="https://user-images.githubusercontent.com/12717324/88194186-228fb400-cc04-11ea-98ac-19c1f29a9e34.png">

**Comment by robb-romans** [comment]
We're not able to reproduce this.
