### ISSUE TITLE
Bug: Bullet points and numbered lists not displayed on blog snippet

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/technical-blog#80]
On page: https://docs-technical-blog.netlify.app/blog/page/36/

The snippet text for Openstack CLI Basics doesn't display bullet points. The bullets are present in the full blog post.

Old version:
![Screen Shot 2020-07-22 at 10 18 20 AM](https://user-images.githubusercontent.com/12717324/88194762-cda06d80-cc04-11ea-940e-c328eba79d1d.png)

New version:
<img width="900" alt="Screen Shot 2020-07-22 at 10 18 15 AM" src="https://user-images.githubusercontent.com/12717324/88194794-d6913f00-cc04-11ea-8e3e-91ad88136036.png">

**Comment by stephamon** [comment]
This seems to be a consistent bug as I encountered it again on Using Cloud-init with Rackspace Cloud (Feb 11, 2014)

**Comment by stephamon** [comment]
This also applies to numbered lists.

Old version:
![Screen Shot 2020-07-22 at 11 11 23 AM](https://user-images.githubusercontent.com/12717324/88200633-0859d400-cc0c-11ea-87c2-f0caaba83650.png)

New version:
<img width="598" alt="Screen Shot 2020-07-22 at 11 11 28 AM" src="https://user-images.githubusercontent.com/12717324/88200646-0bed5b00-cc0c-11ea-9531-e3283ab19167.png">

**Comment by robb-romans** [comment]
Confirmed fixed
![image](https://user-images.githubusercontent.com/730187/88432328-99be7700-cdc1-11ea-9f36-e795d20b53ec.png)
