### ISSUE TITLE
Bug: No indentation for bulleted lists

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/technical-blog#81]
Seeing consistently that bulleted lists are not indented. The bullet mark actually is further left than the start of the surrounding paragraphs:

<img width="581" alt="Screen Shot 2020-07-22 at 10 23 56 AM" src="https://user-images.githubusercontent.com/12717324/88195261-74850980-cc05-11ea-9d25-dc51c6f7de9f.png">

Traditionally bulleted lists are indented from the paragraph text, so it looks a little odd for the bullets not to be offset.

**Comment by robb-romans** [comment]
Fixed
