### ISSUE TITLE
Bug: Code blocks are rendering differently

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/technical-blog#82]
The code blocks have the correct monospace font, but there's nothing else to distinguish them from surrounding text. This makes it a little difficult to spot code blocks quickly. This example is from https://docs-technical-blog.netlify.app/blog/using-cloud-init-with-rackspace-cloud/

Old version:
![Screen Shot 2020-07-22 at 10 27 02 AM](https://user-images.githubusercontent.com/12717324/88195667-e8bfad00-cc05-11ea-9a6f-cab278058696.png)

New version:
<img width="1130" alt="Screen Shot 2020-07-22 at 10 26 50 AM" src="https://user-images.githubusercontent.com/12717324/88195696-ed846100-cc05-11ea-98b2-5b21ab66e7cb.png">

I'm not married to block background code blocks, but maybe indenting them would make it easier to distinguish from the surrounding text.

**Comment by stephamon** [comment]
This might be a bug that affects some posts and not others. Seeing some blog posts that have black background code blocks, such as https://docs-technical-blog.netlify.app/blog/powershell-101-from-a-linux-guy/

**Comment by stephamon** [comment]
Looks like blocks that are rendering with a black background has source code like this in both legacy and new versions:
```
{% highlight yaml %}
- name: Loadbalancer Data Gathering
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: discover load balancer details
      rax_clb: name=app-lb1 port=80 protocol=HTTP type=PUBLIC
               state=present wait=true
               credentials=/path/to/credentials
      register: lb
{% endhighlight %}
```

The code blocks that don't have black backgrounds just use the markdown convention of indenting by four spaces.

**Comment by stephamon** [comment]
Code blocks that use the three backtick method are also displaying without the black background. In https://docs-technical-blog.netlify.app/blog/cancelling-ajax-requests-in-angularjs-applications/ : 
```
```javascript
function createResource(config) {
 var actions = config.actions || {},
 resource,
 outstanding = [];

 resource = $resource(config.url, config.options, actions);

 Object.keys(actions).forEach(function(action) {
   var method = resource[action];

   resource[action] = function() {
    var deferred = $q.defer(),
    promise = method.apply(null, arguments).$promise;

    abortablePromiseWrap(promise, deferred, outstanding);

    return {
      promise: deferred.promise,

      abort: function (){
       deferred.reject('Aborted');
      }
    };
   };
 });

 /**
 * Abort all the outstanding requests on
 * this $resource. Calls promise.reject() on outstanding [].
 */
 resource.abortAll = function () {
  _.invoke(outstanding, 'reject', 'Aborted all');
  outstanding = [];
 };

 return resource;
 }```
```

**Comment by robb-romans** [comment]
Post-release

**Comment by cristiscu** [comment]
This should be fixed, as it looks pretty bad on the published pages.

This is what we see in GitHub:
![image](https://user-images.githubusercontent.com/9575369/173910462-0b1dcb9d-d42f-4fba-9c4f-2350d60a8b08.png)

And this is how it's rendered on the blog:
![image](https://user-images.githubusercontent.com/9575369/173910544-da7c530b-f124-49c5-a486-e31889ce6f96.png)

**Comment by cristiscu** [comment]
To fix the source code in [this page](https://docs.rackspace.com/blog/cancelling-ajax-requests-in-angularjs-applications/) must add "**border: none;**" to the "pre code" style in the source of /opt/build/repo/assets/base/fa.scss:

```
pre code {
    border-radius: 0;
    color: #e0e0d7;
    padding: 0;
    border: none;
}
```

**Comment by cristiscu** [comment]
In the same file, the style for "pre" should be:

```
pre {
    padding: 16px;
    overflow: auto;
    font-size: 85%;
    line-height: 1.45;
    background-color: #f6f8fa;
    border-radius: 6px;
}
```

**Comment by cristiscu** [comment]
@bhaskarboserackspace - could you have a look at my last comments here? Do you know where you can add/change this CSS?
