### ISSUE TITLE
Bug: Numbered list not displaying numbers

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/technical-blog#83]
For post: https://docs-technical-blog.netlify.app/blog/the-odd-couple-mongodb-and-mysql/

The numbered list doesn't display any numbers.

Old version:
![Screen Shot 2020-07-22 at 10 31 40 AM](https://user-images.githubusercontent.com/12717324/88196156-7c917900-cc06-11ea-9c6c-acd638c3d42e.png)

New version:
<img width="930" alt="Screen Shot 2020-07-22 at 10 31 46 AM" src="https://user-images.githubusercontent.com/12717324/88196174-831ff080-cc06-11ea-94b9-0e37c3673ae4.png">

**Comment by stephamon** [comment]
Occurs in https://docs-technical-blog.netlify.app/blog/rolling-deployments-with-ansible-and-cloud-load-balancers/ as well

**Comment by stephamon** [comment]
https://docs-technical-blog.netlify.app/blog/how-we-run-ironic-and-you-can-too/ shows this issue too

**Comment by stephamon** [comment]
https://docs-technical-blog.netlify.app/blog/the-not-so-sorry-state-of-ssl-in-python/

**Comment by stephamon** [comment]
https://docs-technical-blog.netlify.app/blog/adding-devices-to-an-existing-swift-cluster/

**Comment by catlook** [comment]
weird, I reported this in issue https://github.com/rackerlabs/technical-blog/issues/55, and Ravi closed the issue.

**Comment by robb-romans** [comment]
Confirmed fixed
