### ISSUE TITLE
Bug: Paragraph text pulled into code block with HTML tags

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/technical-blog#84]
In post: https://docs-technical-blog.netlify.app/blog/protecting-sensitive-information-from-appearing-in-public-repos/

There's a section where after a code block ends, the following paragraphs are displayed as part of the code in HTML format.

Old version:
![Screen Shot 2020-07-22 at 10 34 42 AM](https://user-images.githubusercontent.com/12717324/88196609-04778300-cc07-11ea-8d1f-1429281de485.png)

New version:
<img width="1119" alt="Screen Shot 2020-07-22 at 10 34 36 AM" src="https://user-images.githubusercontent.com/12717324/88196628-093c3700-cc07-11ea-90f6-4964dd8386e6.png">

**Comment by robb-romans** [comment]
Confirmed fixed.
