### ISSUE TITLE
Bug: Table not displaying with table formatting

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/technical-blog#85]
Post: https://docs-technical-blog.netlify.app/blog/powershell-101-from-a-linux-guy/

At the end of the post, there's meant to be a table in the "Quick reference" section that's just formatting as a block of text.

Old version:
![Screen Shot 2020-07-22 at 10 38 16 AM](https://user-images.githubusercontent.com/12717324/88197074-92536e00-cc07-11ea-81ec-ac38cc76f1e8.png)

New version:
<img width="1155" alt="Screen Shot 2020-07-22 at 10 38 21 AM" src="https://user-images.githubusercontent.com/12717324/88197080-967f8b80-cc07-11ea-8df4-485c9c04e0fb.png">

This is how the table code is in the legacy version:
```
Bash/Linux | PowerShell
--- | ---
ls | ls
mv | mv
cp | cp
pwd | pwd
rm | rm
cat | cat
grep | search-string
echo | echo
var=0 | $var=0
df | gdr or Get-PSdrive
wc | measure-object
ps | ps
find | gci
diff | diff
kill | kill
time | measure-command
if [condition] then something fi | if (condition) { something }
-e file | Test-Path file
for ((i=0; i < 10; i++)) ;  do  echo $i ; done | for ($i=0;$i -lt 10; $i++) { echo $i }
```

But this is how it looks in the new version:
```
Bash/Linux | PowerShellslug: ''   --- | ---
ls | ls
mv | mv
cp | cp
pwd | pwd
rm | rm
cat | cat
grep | search-string
echo | echo
var=0 | $var=0
df | gdr or Get-PSdrive
wc | measure-object
ps | ps
find | gci
diff | diff
kill | kill
time | measure-command
if [condition] then something fi | if (condition) { something }
-e file | Test-Path file
for ((i=0; i < 10; i++)) ;  do  echo $i ; done | for ($i=0;$i -lt 10; $i++) { echo $i }
```

So it looks like one of the table rows at the beginning isn't where it should be, causing the table to not form correctly. Not sure if this is a consistent issue yet or a one-off.

**Comment by robb-romans** [comment]
Confirmed fixed
