### ISSUE TITLE
Bug: AWS and OSAD categories rendering oddly

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/technical-blog#86]
The AWS category in the list under each blog post shows up with odd spacing:

<img width="888" alt="Screen Shot 2020-07-22 at 10 59 41 AM" src="https://user-images.githubusercontent.com/12717324/88199407-71d8e300-cc0a-11ea-87f2-7d79bbbcba51.png">

This is consistent even if you click on the AWS category to view all posts with that topic.

**Comment by stephamon** [comment]
<img width="728" alt="Screen Shot 2020-07-22 at 11 09 19 AM" src="https://user-images.githubusercontent.com/12717324/88200428-bdd85780-cc0b-11ea-9db6-90121b53d0ce.png">

**Comment by catlook** [comment]
This is similar to https://github.com/rackerlabs/technical-blog/issues/57 which noted odd display of SDK

**Comment by robb-romans** [comment]
Confirmed fixed.
