### ISSUE TITLE
Bug: Images don't display in the snippet text

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/technical-blog#87]
In the list of blog posts, images that are in the snippet text don't display:

Old version:
![Screen Shot 2020-07-22 at 11 04 11 AM](https://user-images.githubusercontent.com/12717324/88199981-1ce99c80-cc0b-11ea-8d14-690613cbfc5c.png)

New version:
<img width="1061" alt="Screen Shot 2020-07-22 at 11 04 15 AM" src="https://user-images.githubusercontent.com/12717324/88199997-21ae5080-cc0b-11ea-9fbb-5c680f451a11.png">

**Comment by catlook** [comment]
All posts experiencing this problem are described in https://github.com/rackerlabs/technical-blog/issues/62

**Comment by robb-romans** [comment]
Confirmed fixed.
