### ISSUE TITLE
Bug: Racker banner across author image doesn't appear

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/technical-blog#88]
The little "Racker" banner that is across author images doesn't show up in the beta version.

Old version:
![Screen Shot 2020-07-22 at 11 04 11 AM](https://user-images.githubusercontent.com/12717324/88200083-45719680-cc0b-11ea-8bd5-2ac396d25ccf.png)

New version:
<img width="1061" alt="Screen Shot 2020-07-22 at 11 04 15 AM" src="https://user-images.githubusercontent.com/12717324/88200092-4a364a80-cc0b-11ea-9d32-db2adb77a0bd.png">

**Comment by stephamon** [comment]
This happens without a specific image too:

Old version:
![Screen Shot 2020-07-22 at 11 08 14 AM](https://user-images.githubusercontent.com/12717324/88200305-9a151180-cc0b-11ea-93ba-64ebf344a0a0.png)

New version:
<img width="745" alt="Screen Shot 2020-07-22 at 11 08 10 AM" src="https://user-images.githubusercontent.com/12717324/88200337-a5683d00-cc0b-11ea-8a5a-a4bce46629df.png">

**Comment by robb-romans** [comment]
Based on user research, the banner is removed.
