### ISSUE TITLE
Move static files to page bundles

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/technical-blog#89]
Open separate issue to update contributing guide and writer's handbook as needed

**Comment by codebyravi** [comment]
I moved all the images to their respective dirs.

**Comment by robb-romans** [comment]
@codebyravi thanks
Please put "Closes #89" in the commit message or in a comment in the PR that makes this change

**Comment by robb-romans** [comment]
Fixed by https://github.com/rackerlabs/technical-blog/pull/93
