### ISSUE TITLE
Local hugo server build is not working

### ISSUE THREAD

**Issue by catlook** [rackerlabs/technical-blog#92]
I was able to use the local hugo server successfully one time yesterday.  The second time I tried with a new local post, it did not show up when I started the server on my machine.   

I cleared out my local repo and refreshed from upstream this morning.  After I made a new local post, I again started the hugo server, but my post does not display.  No apparent errors, but I don't know where to find any logs.

**Comment by codebyravi** [comment]
There might be a metadata issue that the post is not being displayed on the local server.

**Comment by catlook** [comment]
this was pebcak error.  I'm used to getting to the blog I want to see by clicking the blog drop down from the preview link instead of adding /blog to the end of the preview URL.  I'll close this and open a new issue for that.
