### ISSUE TITLE
White space around images

### ISSUE THREAD

**Issue by catlook** [rackerlabs/technical-blog#95]
There is a blank line before an image but no blank line after one, if the following line is any header other than a ### header. This results in mushed up text.  See the bottom of this test post: https://deploy-preview-94--docs-technical-blog.netlify.app/blog/introducing-oracle-application-express/

**Comment by catlook** [comment]
This could relate to more than just images. Do all headers automatically allocated the same amount of whitespace before and after the header regardless of the content (text, image, another header, and so on) that precedes and follows the header in question?

**Comment by robb-romans** [comment]
Confirmed fixed. Reopen if you see issues.
