### ISSUE TITLE
Preview Link - blog dropdown

### ISSUE THREAD

**Issue by catlook** [rackerlabs/technical-blog#96]
I'm used to clicking the preview link and arriving at the staging landing page and then clicking the **blogs** dropdown and selecting **technical blog**.  In the old system this keeps me in the staging arena and I can see and click my post.  In the new world, clicking **technical blog** takes me out of staging.  Would be nice is it stayed in staging, but not the end of the world if that can't be done.

**Comment by robb-romans** [comment]
Repo branches are specific to that product. There's no way to build all the other repos as part of a PR branch.

**Comment by catlook** [comment]
This was actually fixed a while ago and now works as desired.
