### ISSUE TITLE
Minor issue: Spacing is generally not properly aligned on Microsoft Edge Browser 

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/technical-blog#97]
Footer - menu items are very close together 

![image](https://user-images.githubusercontent.com/29145813/88293635-e0787800-ccc0-11ea-8638-df04e8f9c685.png)

Author bio name and category are centered on existing site but they are top aligned here. 

![image](https://user-images.githubusercontent.com/29145813/88293812-1e759c00-ccc1-11ea-9708-33a93a293830.png)

**Comment by robb-romans** [comment]
Confirmed fixed
